In [35]:
word_list= ["원숭이", "사과", "바나나" , "코끼리", "코끼리", "개"]

In [33]:
#단어별 인덱스 지정
from collections import defaultdict
import numpy as np

def one_hot_encoding(word_list):
    word2id_dic = defaultdict(lambda:len(word2id_dic))

    for w in word_list :
        word2id_dic[w]
    #고유한 단어 수 
    n_unique_words = len(word2id_dic)
    one_hot_vectors = np.zeros((len(word_list), n_unique_words))
    #원핫 백터 생성
    for i, w in enumerate(word_list) :
        index = word2id_dic[w]
        one_hot_vectors[i , index] = 1

    return one_hot_vectors

In [36]:
one_hot_encoding(word_list)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
def one_hot_encoding_sklearn(word_list):
    #문자에 숫자를 부여
    label_enc = LabelEncoder()
    int_enc = label_enc.fit_transform(word_list)
    #원핫인코딩
    onehot_enc = OneHotEncoder(sparse = False)
    int_enc = int_enc.reshape(len(int_enc), 1)
    onehot_vectors = onehot_enc.fit_transform(int_enc)
    return onehot_vectors

In [58]:
int_enc.reshape(len(int_enc), 1)
#순서는 가나다 순

array([[3],
       [2],
       [1],
       [4],
       [4],
       [0]])

In [67]:
onehot_vectors

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [66]:
word_embbedding_dic = {
    "사과" : [1.0, 0.5],
    "바나나" : [0.9, 1.2],
    "원숭이" : [0.5, 1.5]
}

In [65]:
a = word_embbedding_dic["사과"]
b = word_embbedding_dic ["바나나"]

def euclidean_diat(a, b):
    x = np.array(a)
    y = np.array(b)

    return np.sqrt(np.sum((x-y)**2))


In [68]:
euclidean_diat(a, b)

0.7071067811865475

In [71]:
s1 = "대부분의 원숭이는 바나나를 좋아합니다"
s2 = "코주부 원숭이는 바나나를 싫어합니다"

#실제로 코주부 원숭이는 바나나를 먹으면 죽는다고 하네요. 

In [77]:
def jaccard_index(s1 ,s2):
    token_s1 = s1.split()
    token_s2 = s2.split()

    union = set(token_s1).union(set(token_s2))

    intersection = set(token_s1).intersection(token_s2)

    return len(intersection)/len(union)

In [76]:
jaccard_index(s1 ,s2)

0.3333333333333333

In [78]:
def cosine_similarity(a, b):
    n = np.dot(a, b)
    d = np.linalg.norm(a) * np.linalg.norm(b)
    return n / d


In [79]:
cosine_similarity(a, b)

0.8944271909999159

In [83]:
euclidean_diat(word_embbedding_dic ["바나나"], b)

0.0

In [84]:
cosine_similarity(word_embbedding_dic ["바나나"], b)

1.0